Controllers/WallController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _8_The_Wall.Models;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;

namespace _8_The_Wall.Controllers;

[SessionCheck]
public class WallController : Controller
{
    private readonly ILogger<WallController> _logger;
    public MyContext db;
    public WallController(ILogger<WallController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }

    [HttpGet("messages")]
    public IActionResult Index()
    {
        List<Message> allMessages = db.Messages.Include(m => m.Poster).Include(m => m.Comments).ThenInclude(c => c.User).ToList();
        return View(allMessages);
    }

    [HttpPost("messages/create")]
    public IActionResult CreateMessage(Message newMessage)
    {
        if (!ModelState.IsValid)
        {
            List<Message> allMessages = db.Messages.Include(m => m.Poster).Include(m => m.Comments).ThenInclude(c => c.User).ToList();
            return View("Index", allMessages);
        }
        Console.WriteLine("add message to db");
        db.Messages.Add(newMessage);
        db.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpPost("messages/{messageId}/destroy")]
    public IActionResult DestroyMessage(int messageId)
    {
        Message? msgInDB = db.Messages.FirstOrDefault(m => m.MessageId == messageId);
        if (msgInDB == null || msgInDB.UserId != HttpContext.Session.GetInt32("UserId"))
        {
            return RedirectToAction("Index");
        }
        db.Messages.Remove(msgInDB);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpPost("comments/create")]
    public IActionResult CreateComment(Comment newComment)
    {
        if (!ModelState.IsValid)
        {
            List<Message> allMessages = db.Messages.Include(m => m.Poster).Include(m => m.Comments).ThenInclude(c => c.User).ToList();
            return View("Index", allMessages);
        }

        db.Comments.Add(newComment);
        db.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpPost("comments/{commentId}/destroy")]
    public IActionResult DestroyComment(int commentId)
    {
        Comment? commentInDB = db.Comments.FirstOrDefault(c => c.CommentId == commentId);
        if (commentInDB == null || commentInDB.UserId != HttpContext.Session.GetInt32("UserId"))
        {
            return RedirectToAction("Index");
        }
        db.Comments.Remove(commentInDB);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}
public class SessionCheckAttribute : ActionFilterAttribute
{
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        int? userId = context.HttpContext.Session.GetInt32("UserId");
        if(userId == null)
        {
            context.Result = new RedirectToActionResult("Index", "Home", null);
        }
    }
}

Views/Wall/Index.cshtml
@model List<Message>
<div>
    <h3>Post a message</h3>
    @await Html.PartialAsync("_PostMessage", new Message())
</div>
<div>
    @await Html.PartialAsync("_ShowMessages", Model)
</div>

Views/Wall/_PostComment.cshtml
@model Comment
<textarea id="message" asp-for="CommentText" rows="3"></textarea>
<div class="d-flex justify-content-end gap-3">
    <span asp-validation-for="CommentText" class="text-danger mt-2"></span>
    <button class="btn btn-primary shadow mt-2">Comment</button>
</div>

Views/Wall/_PostMessage.cshtml
@model Message
<form asp-controller="Wall" asp-action="CreateMessage" method="post">
    <input type="hidden" asp-for="UserId" value=@Context.Session.GetInt32("UserId")>
    <textarea id="message" asp-for="MessageText" rows="3"></textarea>
    <div class="d-flex justify-content-end gap-3">
        <span asp-validation-for="MessageText" class="text-danger mt-2"></span>
        <button class="btn btn-success shadow mt-2">Post</button>
    </div>
</form>

Views/Wall/_ShowMessages.cshtml
@model List<Message>
@foreach(Message msg in Model)
{
    <div class="container shadow mb-3 p-3">
        <div class="d-flex justify-content-between">
            <h3>@msg.Poster.FirstName @msg.Poster.LastName - @msg.CreatedAt.ToString("MMMM dd, yyyy")</h3>
        @if(msg.UserId == Context.Session.GetInt32("UserId"))
        {
            <form asp-controller="Wall" asp-action="DestroyMessage" asp-route-messageId=@msg.MessageId>
                <button class="btn btn-danger">Delete Message</button>
            </form>
        }
        </div>
        <p class="ps-2 pe-2">@msg.MessageText</p>
        @foreach(Comment c in msg.Comments)
        {
            <div class="d-flex justify-content-between">
                <p class="ps-4 pe-4 fw-bold">@c.User.FirstName @c.User.LastName - @c.CreatedAt.ToString("MMMM dd, yyyy")</p>
            @if(c.UserId == Context.Session.GetInt32("UserId"))
            {
                <form asp-controller="Wall" asp-action="DestroyComment" asp-route-commentId=@c.CommentId>
                    <button class="btn btn-outline-danger">Delete Comment</button>
                </form>
            }
            </div>
            <p class="ps-5 ps-5">@c.CommentText</p>
        }

        <form asp-controller="Wall" asp-action="CreateComment" method="post" class="ps-4 pe-4">
            <label for="comment" class="fw-bold mb-1">Post a comment</label>
            <input type="hidden" name="UserId" value=@Context.Session.GetInt32("UserId")>
            <input type="hidden" name="MessageId" value=@msg.MessageId>
            @await Html.PartialAsync("_PostComment", new Comment())
        </form>
    </div>
}